version: "3"

services:

  message-broker:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    command: rabbitmq-server
    expose:
      - 5672
      - 15672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1

  microservice_b:
    image: microservice_b-image
    restart: on-failure
    depends_on:
      - message-broker

  microservice_a:
    image: microservice_a-image
    restart: on-failure
    depends_on:
      - message-broker



